routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});



Route::prefix('admin')->middleware(['auth', 'admin'])->group(function () {
    


    Route::get('/', [App\Http\Controllers\Controller::class , 'index'])->name('dashboard');

    Route::controller(App\Http\Controllers\UserController::class)->prefix('users')->name('users.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('{id}/show', 'show')->name('show');
        Route::post('{id}/edit', 'edit')->name('edit');
        Route::get('create', 'create')->name('create');
        Route::post('store', 'store')->name('store');
        Route::get('/delete/{id}', 'destroy')->name('destroy');
    });

    Route::controller(App\Http\Controllers\ProductController::class)->prefix('product')->name('product.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('{id}/show', 'show')->name('show');
        Route::post('{id}/edit', 'edit')->name('edit');
        Route::get('create', 'create')->name('create');
        Route::post('store', 'store')->name('store');
        Route::get('/delete/{id}', 'destroy')->name('destroy');
    });

    Route::controller(App\Http\Controllers\CategoryController::class)->prefix('category')->name('category.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('{id}/show', 'show')->name('show');
        Route::post('{id}/edit', 'edit')->name('edit');
        Route::get('create', 'create')->name('create');
        Route::post('store', 'store')->name('store');
        Route::get('/delete/{id}', 'destroy')->name('destroy');
    });

    Route::controller(App\Http\Controllers\InvoiceController::class)->prefix('invoice')->name('invoices.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/detail/{id}', 'detail')->name('detail');
    });
});

Route::get('/', [App\Http\Controllers\template\ProductController::class , 'home'])->name('home');
Route::get('/product_category/{id}', [App\Http\Controllers\template\ProductController::class , 'viewProduct'])->name('product');
Route::get('/product', [App\Http\Controllers\template\ProductController::class , 'indexProduct'])->name('products.index');
Route::get('/product/{id}', [App\Http\Controllers\template\ProductController::class , 'show'])->name('product.detail');

Route::controller(App\Http\Controllers\template\ProductController::class)->prefix('cart')->group(function () {
    Route::get('/', 'cart')->name('cart');
    Route::get('/add-cart/{id}', 'addCart')->name('addCart');
    Route::post('/update-cart', 'updateCart')->name('updateCart');
    Route::post('/post-cart', 'postCart')->name('postCart');
});


Route::get('/login', [App\Http\Controllers\template\ProductController::class , 'login'])->name('login');
Route::post('/postLogin', [App\Http\Controllers\template\ProductController::class , 'postLogin'])->name('postLogin');
Route::get('/logout', [App\Http\Controllers\template\ProductController::class , 'logout'])->name('logout');

Route::get('/registration', [App\Http\Controllers\template\ProductController::class , 'registration'])->name('registration');
Route::post('/store-regist', [App\Http\Controllers\template\ProductController::class , 'storeRegist'])->name('storeRegist');


Route::controller(App\Http\Controllers\ResetPasswordController::class)->prefix('resetPassword')->name('resetPassword.')->group(function () {

    Route::get('create', 'create')->name('create');

    Route::post('store', 'store')->name('store');

    Route::get('reset-password/{token}', 'showResetPasswordForm')->name('resetPassword');

    Route::post('reset-password', 'submitResetPasswordForm')->name('reset.password.post');
});

Route::get('/contact', function (){
    return view('contact');
})->name('contact');

resources/views/cart.blade.php
@extends('layouts.app')

@section('content')
    <!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Shopping Cart</h1>
                    <nav class="d-flex align-items-center">
                        <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="category.html">Cart</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

    <!--================Cart Area =================-->
    <section class="cart_area">
        @if(session('cart'))

        <div class="container">
            <div class="cart_inner">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th scope="col">Product</th>
                                <th scope="col">Price</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Total</th>
                            </tr>
                        </thead>
                        <form action="{{ route('updateCart') }}" method="POST">
                            @csrf
                            <tbody>
                            <?php $total = 0 ?>

                                @foreach(session('cart') as $id => $details)
                                        <?php $total += $details['price'] * $details['quantity'] ?>
                                        <tr>
                                            <input type="hidden" name="id[]" value="{{ $id }}" />
                                            <td>
                                                <div class="media">
                                                    <div class="d-flex">
                                                        <img src="{{ $details['image'] != '' ? asset('storage/image/'.$details['image'] ) : '' }}" width="60px" alt="">
                                                    </div>
                                                    <div class="media-body">
                                                        <p>{{ $details['name'] }}</p>
                                                    </div>
                                                </div>
                                            </td>
                                            <td>
                                                <h5 id="price-{{ $id }}">@convert($details['price'])</h5>
                                            </td>
                                            <td>
                                                <div class="product_count">
                                                    <input type="text" name="qty[]" id="sst-{{ $id }}" maxlength="12" value="{{ $details['quantity'] }}" title="Quantity:"
                                                           class="input-text qty">
                                                    <input type="hidden" id="sst-default-{{ $id }}" maxlength="12" value="{{ $details['quantity'] }}"
                                                           class="input-text">
                                                    <button onclick="
                                                        var result = document.getElementById('sst-{{ $id }}');
                                                        var defaultResult = document.getElementById('sst-default-{{ $id }}').value;
                                                        var sst = result.value;
                                                        if( !isNaN( sst )) result.value++;
                                                        var updateCart = document.getElementById('btn-cart-update');
                                                        var ddd = result.value;
                                                         if( ddd === defaultResult){
                                                               updateCart.classList.remove('bg-warning');
                                                         }else{
                                                             updateCart.classList.add('bg-warning');
                                                         }
                                                        return false;"
                                                            class="increase items-count" type="button"><i class="lnr lnr-chevron-up"></i></button>
                                                    <button onclick="
                                                        var result = document.getElementById('sst-{{ $id }}');
                                                        var defaultResult = document.getElementById('sst-default-{{ $id }}').value;

                                                        var sst = result.value;
                                                        if( !isNaN( sst ) &amp;&amp; sst > 0 ) result.value--;

                                                        var updateCart = document.getElementById('btn-cart-update');
                                                        var ddd = result.value;
                                                         if( ddd === defaultResult){
                                                               updateCart.classList.remove('bg-warning');
                                                         }else{
                                                             updateCart.classList.add('bg-warning');

                                                         } return false;"
                                                            class="reduced items-count" type="button"><i class="lnr lnr-chevron-down"></i></button>
                                                </div>
                                            </td>
                                            <td>
                                                <h5>@convert($details['price'] * $details['quantity'])</h5>
                                            </td>
                                        </tr>
                                @endforeach
                                <tr class="bottom_button">
                                    <td>
                                        <button name="action" value="updateCart"  type="submit" class="gray_btn" id="btn-cart-update" href="#">Update Cart</button>
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                        <h5>Subtotal</h5>
                                    </td>
                                    <td>
                                        <h5>@convert($total)</h5>
                                    </td>
                                </tr>
                                <tr class="shipping_area">
                                    <td>

                                    </td>
                                    <td>

                                    </td>
                                </tr>
                                <tr class="out_button_area">
                                    <td>
                                    </td>
                                    <td>
                                    </td>
                                    <td>
                                    <td>
                                        <div class="checkout_btn_inner d-flex align-items-center">
                                            <a class="gray_btn" href="#">Back</a>
                                            <button name="action" value="postToConfirm" type="submit" class="border-0 primary-btn" href="#">Proceed to checkout</button>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </form>
                    </table>
                </div>
            </div>
        </div>
        @elseif(!Auth::check())
            <div class="d-flex justify-content-center">
                <h3>You need Login account. <a href="{{ route('login') }}">Login!</a></h3>
            </div>
        @else
            <div class="d-flex justify-content-center">
                <h3>This cart is empty. <a href="{{ route('products.index') }}">Buy Now!</a></h3>
            </div>
        @endif
    </section>
    <!--================End Cart Area =================-->

@endsection

@section('javascript')
    <script type="text/javascript">
     </script>
@endsection

resources/views/check_email.blade.php
<h2>Xin chào thằng: {{$name}}  </h2>

<h2>Forget Password Email</h2>
   
You can reset password from bellow link:

<a href="{{ route('resetPassword.resetPassword' , ['token' => $forgot_token ] ) }}">Reset Password</a> 

resources/views/confirm_cart.blade.php
@extends('layouts.app')

@section('content')
    <!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Shopping Cart</h1>
                    <nav class="d-flex align-items-center">
                        <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="category.html">Cart</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

    <!--================Cart Area =================-->
    <section class="cart_area pt-3">
        @if(session('cart'))
                <form action="{{ route('postCart') }}" method="post">
                    @csrf
                    <input type="hidden" name="id_user" value="{{ Auth::id() }}" />
                <div class="col-6 m-auto">
                    <h3 class="mb-30 text-center">Purchase Information</h3>
                    <div class="section-top-border mt-2">
                        <div class="progress-table-wrap">
                            <div class="progress-table">
                                <div class="table-head">
                                    <div class="serial">#</div>
                                    <div class="country">Name</div>
                                    <div class="visit">Quantity</div>
                                    <div class="percentage">Price</div>
                                </div>
                                    <?php $total = 0;
                                    $number = 1;
                                    ?>
                                @foreach(session('cart') as $id => $details)
                                        <?php $total += $details['price'] * $details['quantity'] ?>
                                    <input type="hidden" name="id_product[]" value="{{ $id }}" />
                                    <div class="table-row">
                                        <div class="serial">{{$number++}}</div>
                                        <div class="country"> <img src="{{ $details['image'] != '' ? asset('storage/image/'.$details['image'] ) : '' }}" width="60px" /></div>
                                        <div class="visit">{{ $details['quantity'] }}</div>
                                        <div class="percentage">
                                            @convert($details['price'] * $details['quantity'])
                                        </div>
                                    </div>
                                @endforeach
                            </div>
                        </div>
                    </div>
                    <div class="checkout_btn_inner d-flex justify-content-end mt-3 mb-3">
                        <h4>Total : @convert($total)</h4>
                        <input name="total" type="hidden" value="{{ $total }}"/>
                    </div>
                    <div class="mt-10">
                        <input type="text" name="name_buyer" value="{{ Auth::user()->name }}" placeholder="Name" onfocus="this.placeholder = ''"
                               onblur="this.placeholder = 'Name'"
                               required class="single-input-primary">
                    </div>

                    <div class="mt-10">
                        <input type="text" value="{{ Auth::user()->email }}" name="email" placeholder="Email address" onfocus="this.placeholder = ''"
                               onblur="this.placeholder = 'Email address'"
                               required class="single-input-primary">
                    </div>
                    <div class="mt-10">
                        <input type="text" name="phone" placeholder="Phone" onfocus="this.placeholder = ''"
                               onblur="this.placeholder = 'Phone'"
                               required class="single-input-primary">
                    </div>
                    <div class="mt-10">
                        <input type="text" name="address" placeholder="Address" onfocus="this.placeholder = ''"
                               onblur="this.placeholder = 'Address'"
                               required class="single-input-primary">
                    </div>
                    <div class="input-group-icon mt-10">
                        <div class="icon"><i class="fa fa-credit-card" aria-hidden="true"></i></div>
                        <div class="form-select" id="default-select">
                            <select name="payment">
                                <option value="1">visit card</option>
                                <option value="2">Cash</option>
                                <option value="3">Transfer</option>
                            </select>
                        </div>
                    </div>
                    <div class="mt-10">
                        <textarea class="single-textarea" placeholder="Note" name="note" onfocus="this.placeholder = ''"
                                  onblur="this.placeholder = 'Note'" required></textarea>
                    </div>
                    <div class="checkout_btn_inner d-flex justify-content-end mt-3">
                        <a class="gray_btn" href="{{ route('cart') }}">Back</a>
                        <button type="submit" class="border-0 primary-btn ml-3" href="#">Submit</button>
                    </div>
                    </div>
                </form>
        @elseif(!Auth::check())
            <div class="d-flex justify-content-center">
                <h3>You need Login account. <a href="{{ route('login') }}">Login!</a></h3>
            </div>
        @else
            <div class="d-flex justify-content-center">
                <h3>This cart is empty. <a href="{{ route('product') }}">Buy Now!</a></h3>
            </div>
        @endif
    </section>
    <!--================End Cart Area =================-->

@endsection

@section('javascript')
    <script type="text/javascript">
    </script>
@endsection

resources/views/forgot_pass.blade.php
{{-- <form class="row " action="{{route('resetPassword.reset.password.post')}}" method="post">
    @csrf
    @if ($errors->any())
            <div class="col-12">
                <div class="alert alert-danger">
                        @foreach ($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                </div>
            </div>
    @endif

    <div class="col-md-12 form-group">PassWord
        <input type="password" class="form-control" id="name" name="password" placeholder="Password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">
    </div>
    <br>
    <div class="col-md-12 form-group">Password Confirmation
        <input type="password" class="form-control" id="name" name="password_confirmation" placeholder="Password Confirmation" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password Confirmation'">
    </div>
    <br>
    <div class="col-md-12 form-group">
        <button type="submit" value="submit" class="primary-btn">Đặt lại mật khẩu</button>
    </div>
</form> --}}
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="author" content="Yinka Enoch Adedokun">
	<meta name="description" content="Simple Forgot Password Page Using HTML and CSS">
	<meta name="keywords" content="forgot password page, basic html and css">
	<title>Forgot Password Page - HTML + CSS</title>
</head>
<body>
    <form class="row " action="{{route('resetPassword.reset.password.post')}}" method="post">
        @csrf
        @if ($errors->any())
                <div class="col-12">
                    <div class="alert alert-danger">
                            @foreach ($errors->all() as $error)
                                <div>{{ $error }}</div>
                            @endforeach
                    </div>
                </div>
        @endif
        <div class="row">
            <h1>Đặt lại mật khẩu</h1>
            <div class="form-group">
                <input type="password" class="form-control" id="name" name="password" placeholder="Password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">
                <p><label for="username">New Pass</label></p>
    
                <input type="password" class="form-control" id="name" name="password_confirmation" placeholder="Password Confirmation" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password Confirmation'">
                <p><label for="username">Password Confirmation</label></p>
    
                <button type="submit" value="submit" class="primary-btn">Đặt lại mật khẩu</button>
            </div>
        </div>
    </form>
	
</body>
<style>
    * {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: "segoe ui", verdana, helvetica, arial, sans-serif;
    font-size: 16px;
    transition: all 500ms ease; }

    body {
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    text-rendering: optimizeLegibility;
    -moz-font-feature-settings: "liga" on; }

    .row {
    background-color: rgba(20, 120, 200, 0.6);
    color: #fff;
    text-align: center;
    padding: 2em 2em 0.5em;
    width: 90%;
    margin: 2em	auto;
    border-radius: 5px; }
    .row h1 {
        font-size: 2.5em; }
    .row .form-group {
        margin: 0.5em 0; }
        .row .form-group label {
        display: block;
        color: #fff;
        text-align: left;
        font-weight: 600; }
        .row .form-group input, .row .form-group button {
        display: block;
        padding: 0.5em 0;
        width: 100%;
        margin-top: 1em;
        margin-bottom: 0.5em;
        background-color: inherit;
        border: none;
        border-bottom: 1px solid #555;
        color: #eee; }
        .row .form-group input:focus, .row .form-group button:focus {
            background-color: #fff;
            color: #000;
            border: none;
            padding: 1em 0.5em; animation: pulse 1s infinite ease;}
        .row .form-group button {
        border: 1px solid #fff;
        border-radius: 5px;
        outline: none;
        -moz-user-select: none;
        user-select: none;
        color: #333;
        font-weight: 800;
        cursor: pointer;
        margin-top: 2em;
        padding: 1em; }
        .row .form-group button:hover, .row .form-group button:focus {
            background-color: #fff; }
        .row .form-group button.is-loading::after {
            animation: spinner 500ms infinite linear;
            content: "";
            position: absolute;
            margin-left: 2em;
            border: 2px solid #000;
            border-radius: 100%;
            border-right-color: transparent;
            border-left-color: transparent;
            height: 1em;
            width: 4%; }
    .row .footer h5 {
        margin-top: 1em; }
    .row .footer p {
        margin-top: 2em; }
        .row .footer p .symbols {
        color: #444; }
    .row .footer a {
        color: inherit;
        text-decoration: none; }

    .information-text {
    color: #ddd; }

    @media screen and (max-width: 320px) {
    .row {
        padding-left: 1em;
        padding-right: 1em; }
        .row h1 {
        font-size: 1.5em !important; } }
    @media screen and (min-width: 900px) {
    .row {
        width: 50%; } 
    }

</style>

resources/views/login.blade.php
@extends('layouts.app')

@section('content')

	<!-- Start Banner Area -->
	<section class="banner-area organic-breadcrumb">
		<div class="container">
			<div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
				<div class="col-first">
					<h1>Login/Register</h1>
					<nav class="d-flex align-items-center">
						<a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
						<a href="category.html">Login/Register</a>
					</nav>
				</div>
			</div>
		</div>
	</section>
	<!-- End Banner Area -->

	<!--================Login Box Area =================-->
	<section class="login_box_area section_gap">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="login_box_img">
						<img class="img-fluid" src="{{ asset('template/img/login.jpg') }}" alt="">
						<div class="hover">
							<h4>New to our website?</h4>
							<p>There are advances being made in science and technology everyday, and a good example of this is the</p>
							<a class="primary-btn" href="{{ route('registration') }}">Create an Account</a>
						</div>
					</div>
				</div>
				<div class="col-lg-6">
					<div class="login_form_inner">
						<h3>Log in to enter</h3>
						<form class="row login_form" action="{{ route('postLogin') }}" method="post" id="contactForm" novalidate="novalidate">
							@csrf
                            @if ($errors->any())
                                <div class="col-12">
                                    <div class="alert alert-danger">
                                        @foreach ($errors->all() as $error)
                                            <div>{{ $error }}</div>
                                        @endforeach
                                    </div>
                                </div>
                            @endif
                            @if (session()->get('errors_login'))
                                <div class="col-12">
                                    <div class="alert alert-danger">
                                        @foreach ($errors->all() as $error)
                                            <div>{!! session()->get('errors_login') !!}</div>
                                        @endforeach
                                    </div>
                                </div>
                            @endif
                            <div class="col-md-12 form-group">
								<input type="text" class="form-control" id="name" name="email" placeholder="Username" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Username'">
							</div>
							<div class="col-md-12 form-group">
								<input type="password" class="form-control" id="name" name="password" placeholder="Password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Password'">
							</div>
							<div class="col-md-12 form-group">
								<div class="creat_account">
									<input type="checkbox" id="f-option2" name="selector">
									<label for="f-option2">Keep me logged in</label>
								</div>
							</div>
							<div class="col-md-12 form-group">
								<button type="submit" value="submit" class="primary-btn">Log In</button>
								<a href="{{route('resetPassword.create')}}">Forgot Password?</a>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--================End Login Box Area =================-->

@endsection

@section('javascript')

@endsection

resources/views/reset_password.blade.php
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
 <div class="form-gap"></div>
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
            <div class="panel panel-default">
              <div class="panel-body">
                <div class="text-center">
                  <h3><i class="fa fa-lock fa-4x"></i></h3>
                  <h2 class="text-center">Forgot Password?</h2>
                  <p>You can reset your password here.</p>
                  <div class="panel-body">
                        <form id="register-form" action="{{route('resetPassword.store')}}" method="POST">
                            @csrf
                        <div class="form-group">
                            <div class="input-group">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-envelope color-blue"></i></span>
                            <input id="email" name="email" placeholder="email address" class="form-control"  type="email">
                            </div>
                        </div>
                        <button type="submit" class="btn btn-lg btn-primary btn-block">
                            Reset Password
                        </button>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
	</div>
</div>
<style>
    .form-gap {
    padding-top: 70px;
}
</style>

resources/views/thank_you.blade.php
@extends('layouts.app')

@section('content')
    <!-- Start Banner Area -->
    <section class="banner-area organic-breadcrumb">
        <div class="container">
            <div class="breadcrumb-banner d-flex flex-wrap align-items-center justify-content-end">
                <div class="col-first">
                    <h1>Shopping Cart</h1>
                    <nav class="d-flex align-items-center">
                        <a href="index.html">Home<span class="lnr lnr-arrow-right"></span></a>
                        <a href="category.html">Cart</a>
                    </nav>
                </div>
            </div>
        </div>
    </section>
    <!-- End Banner Area -->

    <!--================Cart Area =================-->
    <section class="cart_area pt-3">
            <div class="d-flex justify-content-center">
                <h3>Thank you for your purchase!</h3>
            </div>
    </section>
    <!--================End Cart Area =================-->

@endsection

@section('javascript')
    <script type="text/javascript">
    </script>
@endsection