routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard');
});



Route::prefix('admin')->middleware(['auth', 'admin'])->group(function () {
    


    Route::get('/', [App\Http\Controllers\Controller::class , 'index'])->name('dashboard');

    Route::controller(App\Http\Controllers\UserController::class)->prefix('users')->name('users.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('{id}/show', 'show')->name('show');
        Route::post('{id}/edit', 'edit')->name('edit');
        Route::get('create', 'create')->name('create');
        Route::post('store', 'store')->name('store');
        Route::get('/delete/{id}', 'destroy')->name('destroy');
    });

    Route::controller(App\Http\Controllers\ProductController::class)->prefix('product')->name('product.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('{id}/show', 'show')->name('show');
        Route::post('{id}/edit', 'edit')->name('edit');
        Route::get('create', 'create')->name('create');
        Route::post('store', 'store')->name('store');
        Route::get('/delete/{id}', 'destroy')->name('destroy');
    });

    Route::controller(App\Http\Controllers\CategoryController::class)->prefix('category')->name('category.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('{id}/show', 'show')->name('show');
        Route::post('{id}/edit', 'edit')->name('edit');
        Route::get('create', 'create')->name('create');
        Route::post('store', 'store')->name('store');
        Route::get('/delete/{id}', 'destroy')->name('destroy');
    });

    Route::controller(App\Http\Controllers\InvoiceController::class)->prefix('invoice')->name('invoices.')->group(function () {
        Route::get('/', 'index')->name('index');
        Route::get('/detail/{id}', 'detail')->name('detail');
    });
});

Route::get('/', [App\Http\Controllers\template\ProductController::class , 'home'])->name('home');
Route::get('/product_category/{id}', [App\Http\Controllers\template\ProductController::class , 'viewProduct'])->name('product');
Route::get('/product', [App\Http\Controllers\template\ProductController::class , 'indexProduct'])->name('products.index');
Route::get('/product/{id}', [App\Http\Controllers\template\ProductController::class , 'show'])->name('product.detail');

Route::controller(App\Http\Controllers\template\ProductController::class)->prefix('cart')->group(function () {
    Route::get('/', 'cart')->name('cart');
    Route::get('/add-cart/{id}', 'addCart')->name('addCart');
    Route::post('/update-cart', 'updateCart')->name('updateCart');
    Route::post('/post-cart', 'postCart')->name('postCart');
});


Route::get('/login', [App\Http\Controllers\template\ProductController::class , 'login'])->name('login');
Route::post('/postLogin', [App\Http\Controllers\template\ProductController::class , 'postLogin'])->name('postLogin');
Route::get('/logout', [App\Http\Controllers\template\ProductController::class , 'logout'])->name('logout');

Route::get('/registration', [App\Http\Controllers\template\ProductController::class , 'registration'])->name('registration');
Route::post('/store-regist', [App\Http\Controllers\template\ProductController::class , 'storeRegist'])->name('storeRegist');


Route::controller(App\Http\Controllers\ResetPasswordController::class)->prefix('resetPassword')->name('resetPassword.')->group(function () {

    Route::get('create', 'create')->name('create');

    Route::post('store', 'store')->name('store');

    Route::get('reset-password/{token}', 'showResetPasswordForm')->name('resetPassword');

    Route::post('reset-password', 'submitResetPasswordForm')->name('reset.password.post');
});

Route::get('/contact', function (){
    return view('contact');
})->name('contact');

resources/views/admin/content/add-category.blade.php
@extends('admin.app')

@section('title', 'Category')

@section('header')
    @include('admin.content_head', [
        'pageTitle' => 'Category',
    ])
@endsection

@section('content')
    <div class="card ">
        <div class="card-header">
            <h3 class="card-title">Add New</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" method="post" action="{{ route('category.store') }}">
            @csrf
            <div class="card-body">
                <div class="form-group">
                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-6">
                        <input type="text" name="name" class="form-control" id="name" placeholder="name">
                        @if ($errors->has('name'))
                            <div class="error-validate text-danger">{{ $errors->first('name') }}</div>
                      @endif
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <a href="{{ route('category.index') }}"> <button class="btn btn-secondary">Back</button></a> <button type="submit" class="btn btn-success float-right">Submit</button>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>
@endsection

@section('javascript')
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table-tenants').DataTable({
                serverSide: false,
                lengthChange: true,
                pageLength: 10,
                deferLoading: 20,
            });
        });
    </script>
@endsection

resources/views/admin/content/add-product.blade.php
@extends('admin.app')

@section('title', 'product')

@section('header')
    @include('admin.content_head', [
        'pageTitle' => 'Product',
    ])
@endsection

@section('content')
    <div class="card ">
        <div class="card-header">
            <h3 class="card-title">Add New</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" method="post" action="{{ route('product.store') }}"  enctype="multipart/form-data">
            @csrf
            @if ($errors->any())
                <div class="col-12 mt-4">
                    <div class="alert alert-danger">
                        @foreach ($errors->all() as $error)
                            <div>{{ $error }}</div>
                        @endforeach
                    </div>
                </div>
            @endif
            <div class="card-body">
                <div class="form-group">
                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-6">
                        <input type="text" value="{{ old('name') }}" name="name" class="form-control" id="name" placeholder="name">
                    </div>
                </div>
                <div class="form-group">
                    <label for="price" class="col-sm-2 col-form-label">price</label>
                    <div class="col-sm-6">
                        <input type="text" value="{{ old('price') }}" class="form-control" name="price" id="price" placeholder="price">
                    </div>
                </div>
                <div class="form-group">
                    <label for="price" class="col-sm-2 col-form-label">Category</label>
                    <div class="col-sm-6">
                        <select name="id_category" class="form-control" id="">
                            @foreach($cate as $item)
                            <option value="{{ $item->id }}"> {{ $item->name }} </option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group">
                  <label for="image" class="col-sm-2 col-form-label">Image</label>
                  <div class="col-sm-6">
                    <input type="file" class="form-control" name="image" id="image" placeholder="image">
                  </div>
                </div>
                <div class="form-group">
                  <label for="inputEmail3" class="col-sm-2 col-form-label">Description</label>
                  <div class="col-sm-6">
                      <textarea class="form-control" name="description" id="" cols="30" rows="5">{{ old('description') }}</textarea>
                  </div>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <a href="{{ route('product.index') }}"> <button class="btn btn-secondary">Back</button></a> <button type="submit" class="btn btn-success float-right">Submit</button>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>
@endsection

@section('javascript')
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table-tenants').DataTable({
                serverSide: false,
                lengthChange: true,
                pageLength: 10,
                deferLoading: 20,
            });
        });
    </script>
@endsection

resources/views/admin/content/add-user.blade.php
@extends('admin.app')

@section('title', 'User')

@section('header')
    @include('admin.content_head', [
        'pageTitle' => 'User',
    ])
@endsection

@section('content')
    <div class="card ">
        <div class="card-header">
            <h3 class="card-title">Add New</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" method="post" action="{{ route('users.store') }}">
            @csrf
            <div class="card-body">
                <div class="form-group">
                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-6">
                        <input type="text" name="name" class="form-control" id="name" placeholder="name">
                    </div>
                </div>
                <div class="form-group">
                    <label for="name" class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-6">
                        <input type="email" name="email" class="form-control" id="name" placeholder="Email">
                    </div>
                </div>
                <div class="form-group">
                    <label for="name" class="col-sm-2 col-form-label">Password</label>
                    <div class="col-sm-6">
                        <input type="password" name="password" class="form-control" id="name" placeholder="Password">
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <a href="{{ route('category.index') }}"> <button class="btn btn-secondary">Back</button></a> <button type="submit" class="btn btn-success float-right">Submit</button>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>
@endsection

@section('javascript')
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table-tenants').DataTable({
                serverSide: false,
                lengthChange: true,
                pageLength: 10,
                deferLoading: 20,
            });
        });
    </script>
@endsection

resources/views/admin/content/category.blade.php
@extends('admin.app')

@section('title', 'Category')

@section('header')
    @include('admin.content_head', [
        'pageTitle' => 'Category',
    ])
@endsection

@section('content')
    <div class="card">
        <div class="card-header ui-sortable-handle">
            <h3 class="card-title">
                Category
            </h3>
          <a class="float-right" href="{{ route('category.create') }}"><button class="btn btn-primary" type="button">Add New</button></a>
        </div>
        <div class="card-body">
            <div class="table-content" >
                <table class="table table-bordered table-custom table-users-wrap" id="table-tenants">
                    <thead>
                        <tr>
                            <th width="5%">id</th>
                            <th width="10%">Name</th>
                            <th width="10%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach ($cate as $item)
                         <tr>
                            <td>{{ $item->id }}</td>
                            <td>{{ $item->name }}</td>
                            <td class="text-center">
                               <a href="{{ route('category.show' , $item->id) }}"><button class="btn btn-warning">Edit</button></a>
                               <a href="{{ route('category.destroy' , $item->id) }}"><button class="btn btn-danger">Delete</button></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('javascript')
    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('#table-tenants').DataTable({
                serverSide: false,
                lengthChange : false,
                pageLength: 10,
                deferLoading: 20,
                searching: false
            });
        });
    </script>
@endsection

resources/views/admin/content/dashboard.blade.php
@extends('admin.app')

@section('title', 'product')

@section('header')
    @include('admin.content_head', [
        'pageTitle' => 'Dashboard',
    ])
@endsection


@section('content')
<div class="row">
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-info">
      <div class="inner">
        <h3>{{ $invoice }}</h3>
        <p>New Orders</p>
      </div>
      <div class="icon">
        <i class="ion ion-bag"></i>
      </div>
      <a href="{{ route('invoices.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-success">
      <div class="inner">
        <h3>{{ $users }}</h3>

        <p>Users Registrations</p>
      </div>
      <div class="icon">
        <i class="ion ion-stats-bars"></i>
      </div>
      <a href="{{ route('users.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-warning">
      <div class="inner">
        <h3>{{ $products }}</h3>
        <p>ALL Products</p>
      </div>
      <div class="icon">
        <i class="ion ion-person-add"></i>
      </div>
      <a href="{{ route('product.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <!-- ./col -->
  <div class="col-lg-3 col-6">
    <!-- small box -->
    <div class="small-box bg-danger">
      <div class="inner">
        <h3>{{ $category }}</h3>

        <p>Category Product</p>
      </div>
      <div class="icon">
        <i class="ion ion-pie-graph"></i>
      </div>
      <a href="{{ route('category.index') }}" class="small-box-footer">More info <i class="fas fa-arrow-circle-right"></i></a>
    </div>
  </div>
  <!-- ./col -->
</div>
<div class="card ">
    <div class="card-header">
        <h3 class="card-title">Revenue</h3>
        <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i></button>
        </div>
    </div>
    <!-- /.card-header -->
    <!-- form start -->
        <div class="card-body" >
            <div style="height: 400px;">
                <canvas id="ChartDashboard" ></canvas>
            </div>
        </div>
</div>

@endsection

@section('javascript')
<script type="text/javascript">


    $(document).ready(function () {
        const CHART_COLORS = {
            red: 'rgb(255, 99, 132)',
            orange: 'rgb(255, 159, 64)',
            yellow: 'rgb(255, 205, 86)',
            green: 'rgb(75, 192, 192)',
            blue: 'rgb(54, 162, 235)',
            purple: 'rgb(153, 102, 255)',
            grey: 'rgb(201, 203, 207)'
        };

        const ctx = document.getElementById('ChartDashboard');
        var invoiceTotal = {!! json_encode($invoiceTotal) !!};
        var invoiceCreatedAt = {!! json_encode($invoiceCreatedAt) !!};
        new Chart(ctx, {
            type: 'line',
            data: {
                labels: invoiceCreatedAt,
                datasets: [{
                    label: 'Total Revenue',
                    data: invoiceTotal,
                    borderColor: CHART_COLORS['red'],
                    backgroundColor:CHART_COLORS['red'],
                    fill: false
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
            }
        });
    });
</script>
@endsection

resources/views/admin/content/edit-category.blade.php
@extends('admin.app')

@section('title', 'Category')

@section('header')
    @include('admin.content_head', [
        'pageTitle' => 'Category',
    ])
@endsection

@section('content')
    <div class="card ">
        <div class="card-header">
            <h3 class="card-title">Edit New</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" method="post" action="{{ route('category.edit' , $category->id) }}">
            @csrf
            <div class="card-body">
                <input type="hidden" name="id" value="{{ $category->id }}" />
                <div class="form-group">
                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-6">
                        <input type="text" name="name" class="form-control" id="name"  value="{{ $category->name }}" placeholder="name">
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <a href="{{ route('category.index') }}"> <button class="btn btn-secondary">Back</button></a> <button type="submit" class="btn btn-success float-right">Submit</button>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>
@endsection

@section('javascript')
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table-tenants').DataTable({
                serverSide: false,
                lengthChange: true,
                pageLength: 10,
                deferLoading: 20,
            });
        });
    </script>
@endsection

resources/views/admin/content/edit-product.blade.php
@extends('admin.app')

@section('title', 'product')

@section('header')
    @include('admin.content_head', [
        'pageTitle' => 'Product',
    ])
@endsection

@section('content')
    <div class="card ">
        <div class="card-header">
            <h3 class="card-title">Edit New</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" method="post" action="{{ route('product.edit', $product->id) }}" enctype="multipart/form-data">
            @csrf
            <input type="hidden" name="id" value="{{ $product->id }}">
            <div class="card-body">
                <div class="form-group">
                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-6">
                        <input type="text" name="name" class="form-control" value="{{ $product->name }}" id="name" placeholder="name">
                    </div>
                </div>
                <div class="form-group">
                    <label for="price" class="col-sm-2 col-form-label">Price</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" value="{{ $product->price }}" name="price" id="price" placeholder="price">
                    </div>
                </div>
                <div class="form-group">
                    <label for="price" class="col-sm-2 col-form-label">Category</label>
                    <div class="col-sm-6">
                        <select name="id_category" class="form-control" id="">
                            @foreach($cate as $item)
                                <option value="{{ $item->id }}" @if($product->id_category == $item->id)  selected @endif> {{ $item->name }} </option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="form-group">
                  <label for="image" class="col-sm-2 col-form-label">Image</label>
                  <div class="col-sm-6">
                    <input type="file" class="form-control" name="image" id="image" placeholder="image">
                  </div>
                </div>
                <div class="form-group">
                  <label for="inputEmail3" class="col-sm-2 col-form-label">Description</label>
                  <div class="col-sm-6">
                      <textarea class="form-control" name="description" id="" cols="30" rows="5"> {{ $product->description }}</textarea>
                  </div>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <a href="{{ route('products.index') }}"> <button class="btn btn-secondary">Back</button></a> <button type="submit" class="btn btn-success float-right">Submit</button>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>
@endsection

@section('javascript')
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table-tenants').DataTable({
                serverSide: false,
                lengthChange: true,
                pageLength: 10,
                deferLoading: 20,
            });
        });
    </script>
@endsection

resources/views/admin/content/edit-user.blade.php
@extends('admin.app')

@section('title', 'User')

@section('header')
    @include('admin.content_head', [
        'pageTitle' => 'User',
    ])
@endsection

@section('content')
    <div class="card ">
        <div class="card-header">
            <h3 class="card-title">Edit New</h3>
        </div>
        <!-- /.card-header -->
        <!-- form start -->
        <form class="form-horizontal" method="post" action="{{ route('users.edit', $user->id) }}">
            @csrf
            <div class="card-body">
                <div class="form-group">
                    <label for="name" class="col-sm-2 col-form-label">Name</label>
                    <div class="col-sm-6">
                        <input type="text" name="name" class="form-control" id="name" placeholder="name" value="{{ $user->name }}"/>
                    </div>
                </div>
                <div class="form-group">
                    <label for="name" class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-6">
                        <input type="email" name="email" class="form-control" id="name" placeholder="Email" value="{{ $user->email }}" />
                    </div>
                </div>
                <div class="form-group">
                    <label for="name" class="col-sm-2 col-form-label">Password</label>
                    <div class="col-sm-6">
                        <input type="password" name="password"  class="form-control" id="name" placeholder="Password">
                    </div>
                </div>
            </div>
            <!-- /.card-body -->
            <div class="card-footer">
                <a href="{{ route('users.index') }}"> <button class="btn btn-secondary" type="button">Back</button></a> <button type="submit" class="btn btn-success float-right">Submit</button>
            </div>
            <!-- /.card-footer -->
        </form>
    </div>
@endsection

@section('javascript')
    <script type="text/javascript">
        $(document).ready(function() {
            var table = $('#table-tenants').DataTable({
                serverSide: false,
                lengthChange: true,
                pageLength: 10,
                deferLoading: 20,
            });
        });
    </script>
@endsection

resources/views/admin/content/invoice.blade.php
@extends('admin.app')

@section('title', 'invoice')

@section('header')
    @include('admin.content_head', [
        'pageTitle' => 'invoice',
    ])
@endsection

@section('content')
    <div class="card">
        <div class="card-header ui-sortable-handle">
            <h3 class="card-title">
                invoice
            </h3>
        </div>
        <div class="card-body">
            <div class="table-content" >
                <table class="table table-bordered table-custom table-users-wrap" id="table-tenants">
                    <thead>
                    <tr>
                        <th width="5%">Id</th>
                        <th width="10%">Name Buyer</th>
                        <th width="10%">Phone</th>
                        <th width="10%">Address</th>
                        <th width="10%">Total</th>
                        <th width="10%">Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($invoices as $item)
                        <tr>
                            <td class="text-center"><a href="{{ route('invoices.detail', $item->id) }}" title="Detail"> <button class="btn btn-info">{{ $item->id }}</button></a></td>
                            <td>{{ $item->name_buyer }}</td>
                            <td>{{ $item->phone }}</td>
                            <td>{{ $item->address }}</td>
                            <td>@convert($item->total)</td>
                            <td>{{ $item->created_at }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('javascript')
    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('#table-tenants').DataTable({
                serverSide: false,
                lengthChange : false,
                pageLength: 10,
                deferLoading: 20,
                searching: false
            });
        });
    </script>
@endsection

resources/views/admin/content/product.blade.php
@extends('admin.app')

@section('title', 'product')

@section('header')
    @include('admin.content_head', [
        'pageTitle' => 'Product',
    ])
@endsection

@section('content')
    <div class="card">
        <div class="card-header ui-sortable-handle">
            <h3 class="card-title">
                product
            </h3>
          <a class="float-right" href="{{ route('product.create') }}"><button class="btn btn-primary" type="button">Add New</button></a>
        </div>
        <div class="card-body">
            <div class="table-content" >
                <table class="table table-bordered table-custom table-users-wrap" id="table-tenants">
                    <thead>
                        <tr>
                            <th width="5%">id</th>
                            <th width="10%">Name</th>
                            <th width="10%">Image</th>
                            <th width="10%">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach ($products as $item)
                         <tr>
                            <td>{{ $item->id }}</td>
                            <td>{{ $item->name }}</td>
                            <td><img src="{{ asset('storage/image/'.$item->image ) }}" alt="" width="100px"/></td>
                            <td class="text-center">
                               <a href="{{ route('product.show' , $item->id) }}"><button class="btn btn-warning">Edit</button></a>
                               <a href="{{ route('product.destroy' , $item->id) }}"><button class="btn btn-danger">Delete</button></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('javascript')
<script type="text/javascript">
    $(document).ready(function () {
        var table = $('#table-tenants').DataTable({
            serverSide: false,
            lengthChange : false,
            pageLength: 10,
            deferLoading: 20,
            searching: false
        });
    });
</script>
@endsection

resources/views/admin/content/user.blade.php
@extends('admin.app')

@section('title', 'user')

@section('header')
    @include('admin.content_head', [
        'pageTitle' => 'user',
    ])
@endsection

@section('content')
    <div class="card">
        <div class="card-header ui-sortable-handle">
            <h3 class="card-title">
                User
            </h3>
            <a class="float-right" href="{{ route('users.create') }}"><button class="btn btn-primary" type="button">Add New</button></a>
        </div>
        <div class="card-body">
            <div class="table-content" >
                <table class="table table-bordered table-custom table-users-wrap" id="table-tenants">
                    <thead>
                    <tr>
                        <th width="5%">id</th>
                        <th width="10%">Name</th>
                        <th width="10%">Email</th>
                        <th width="10%">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($users as $item)
                        <tr>
                            <td>{{ $item->id }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->email }}</td>
                            <td class="text-center">
                                <a href="{{ route('users.show' , $item->id) }}"><button class="btn btn-warning">Edit</button></a>
                                <a href="{{ route('users.destroy' , $item->id) }}"><button class="btn btn-danger">Delete</button></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('javascript')
    <script type="text/javascript">
        $(document).ready(function () {
            var table = $('#table-tenants').DataTable({
                serverSide: false,
                lengthChange : false,
                pageLength: 10,
                deferLoading: 20,
                searching: false
            });
        });
    </script>
@endsection